### PR TITLE
Add Separate Results Page

### PR DESCRIPTION
**Pull request by Jonesey13**
Moved the format of the site to a separate results page which highlights concerns (and the PE resistance value):
image

Although it's no longer a single page site I've tried to hide this as much as possible (page refreshes from the results page take you back to the input form for example).

### CODE REVIEW

**Review by Woolfie-T — COMMENTED** [review]
I'm busy today but had a quick look. 
The information is great!
The wording needs some thinking about, it might be good to have a 3 way discussion with Dermot. 
Personally I think the results display could benefit from some borders or backgrounds to make it easier for the eye to take in how it's organised.  
And we need FF branding and link. 
I'm really pleased with the way this has come on. Yesterday I was talking to someone at a party (!) about PAT testing - he had a question and I mentioned this calculator, he was really interested in using it.  He's an engineer who does it when accepting new networking equipment for the BBC so it's not part of his main job but he needs to know; probably a lot of engineers in that situation.

**Comment by Woolfie-T** [comment]
Do you think it's time to post a link on Discord so other people can try it?

**Comment by Woolfie-T** [comment]
Having another look: I think I would prefer the sections "Current drawn ..." and "Fuse Rating ... "  the other way round.  For an appliance with a specified current, the maximum rating of cable and plug is more fundamental than whether the fuse currently fitted is big enough.   Some fuse sizes have been revised downward, but rated current for given cable CSA should still be valid for older equipment - so if this is significantly wrong it probably indicates something that matters.

**Comment by Jonesey13** [comment]
@Woolfie-T I've actioned the comments made above and added some branding/styling/structure and swapped the "Current Drawn" & "Fuse Rating" tables:
image
Any further restyling is probably best discussed with @SLMS-Dermot as you said.

Happy for the new link to be shared on Discord for testing.

**Pull request closed without merging**
